# Generated by Django 5.2.3 on 2025-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
