# Generated by Django 5.2.3 on 2025-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_invoice_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_restored",
            field=models.BooleanField(default=False),
        ),
    ]
