# Generated by Django 5.2.3 on 2025-07-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_stock_restored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stock_restored",
        ),
    ]
